site_name: Tapir's Notebook
site_url: https://tapir-elithril.github.io/Notebook/
site_author: 杨亿酬
site_description: Tapir's Notebook
copyright: Copyright © YYC 2025
extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://tapir-elithril.github.io/Notebook/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<3230105697@zju.edu.cn> #联系方式

nav:
  - 首页: index.md
  - tools: 
    - tools/index.md
    - Git: tools/git/index.md
    - Linux: tools/linux/index.md
    - Markdown: tools/markdown/index.md
    - LaTeX: 
      - tools/latex/index.md
      - 文献: tools/latex/format.md
      - 常用符号: tools/latex/symbols.md
    - Makefile: tools/makefile/index.md
  #   - Html: tools/html/index.md
  #   - reveal-md: tools/reveal-md/index.md
  - fa23:
    - fa23/index.md
    - 军训: fa23/military_training/index.md
    - 数学分析(甲)I(H): fa23/math_analysis1/index.md
    - 程序设计与算法基础: fa23/programming/index.md
    - 线性代数I(H): fa23/linear_algebra1/index.md
    - 中国近现代史纲要(H): fa23/modern_history/index.md
    - 思想道德与法治: fa23/morality_law/index.md
    - 近代西方政治哲学导论: fa23/political_philosophy/index.md
    - 天文学导论: fa23/astronomy/index.md
    - 心理学及应用: fa23/psychology/index.md
    - 职业生涯规划: fa23/career_planning/index.md
    - 中国改革开放史: fa23/reform_and_openup/index.md
    - 定向越野: fa23/orienteering/index.md
    - 身体素质课: fa23/fitness/index.md
  - sp24:
    - sp24/index.md
    - 数学分析(甲)II(H): sp24/math_analysis2/index.md
    - 计算机系统I: 
      - sp24/sys1/index.md
      - 单周期CPU: sp24/sys1/CPU.md
    - 普通物理学I(H): sp24/physics1/index.md
    - 离散数学理论基础: sp24/discrete_math/index.md
    - 线性代数II(H): sp24/linear_algebra2/index.md
    - 数据结构基础: 
      - sp24/fds/index.md
      - 常见结构体: sp24/fds/struct.md
    - 普通物理学实验I: sp24/physics1_lab/index.md
    - 网络空间安全导论: sp24/cyber_security/index.md
    - 打开艺术之门——钢琴: sp24/piano/index.md
    - 游泳(初级): sp24/swimming/index.md
    - 身体素质课: sp24/fitness/index.md
    - 形势与政策I: sp24/situation_policy1/index.md
    - 课程综合实践I——安全攻防实践基础(CTF): sp24/ctf/index.md
  - fa24:
    - fa24/index.md
    - 计算机系统II: 
      - fa24/sys2/index.md
      - 课程笔记: fa24/sys2/note.md
    - 普通物理学II(H): fa24/physics2/index.md
    - 高级数据结构与算法分析: 
      - fa24/ads/index.md
      - 课程笔记: fa24/ads/note.md
    - 概率论(H): fa24/probability/index.md
    - 人工智能引论: fa24/aid/index.md
    - 军事理论: fa24/military_theory/index.md
    - 普通物理学实验II: fa24/physics2_lab/index.md
    - 茶文化与茶健康: fa24/tea/index.md
    - 健美操: fa24/aerobics/index.md
  - sp25:
    - sp25/index.md
    - 计算机系统III:
      - sp25/sys3/index.md
      - 笔记: sp25/sys3/note.md
    - 数据库系统: 
      - sp25/db/index.md
      - 笔记: sp25/db/note.md
    - 面向对象程序设计: 
      - sp25/oop/index.md
      - 笔记: sp25/oop/note.md
    - 马克思主义基本原理(H): sp25/marx/index.md
    - 习近平新时代中国特色社会主义思想概论: sp25/xi/index.md
    - 排舞: sp25/line_dance/index.md
    - 数据要素交易基础:
      - sp25/data_market/index.md
      - 笔记: sp25/data_market/note.md
  - research:
    - data_target:
      - research/data/note.md
      - paper_list: research/data/paper.md
      - review: research/data/review.md
    - kaggle: 
      - research/kaggle/index.md
    - llm_infra:
      - kvcache: research/llm_vuln/kvcache.md
      - llm_vulnerability: research/llm_vuln/llm_vulnerability.md
      - mcp: research/llm_vuln/mcp.md

theme:
  name: material
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: indigo
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      background: "#000000"  # 设置纯黑背景
      surface: "#121212"     # 设置深色表面
      text: "#ffffff"        # 纯白色文本
      anchor: "#ffffff"      # 链接颜色
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
  font:
    code: JetBrains Mono
    text: Noto Serif SC
  language: zh # 一些提示性的文字会变成中文
  # icon:
  #   edit: material/pencil
# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
repo_url: https://github.com/Tapir-Elithril/Notebook
repo_name: Tapir-Elithril/Notebook
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - sane_lists

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js