site_name: Tapir's Notebook
site_url: https://tapir-elithril.github.io/Notebook/
site_author: 杨亿酬
site_description: Tapir's Notebook
copyright: 2025 yyc

theme:
  name: material
  icon:
    edit: material/pencil
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  language: zh
  font:
    code: JetBrains Mono
    text: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 首页: index.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://fonts.googleapis.com/css?family=Roboto:500,500i,600,600i&display=fallback
  - css/custom.css
